# Generated by Django 5.1.4 on 2025-08-10 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_departamento', models.CharField(db_index=True, max_length=20, verbose_name='Número de departamento')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tarifa_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa mensual')),
                ('terminos_adicionales', models.TextField(blank=True, max_length=1000)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('arrendatario', models.ForeignKey(help_text='Usuario de tipo arrendatario asociado al contrato.', on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to=settings.AUTH_USER_MODEL, verbose_name='Arrendatario')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='Periodo (mes)')),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], db_index=True, default='pendiente', max_length=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20, null=True)),
                ('referencia', models.CharField(blank=True, help_text='Número de transacción o referencia', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='inicio.contrato')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recordatorio_pago', 'Recordatorio de pago'), ('pago_vencido', 'Pago vencido'), ('fin_contrato', 'Fin de contrato')], db_index=True, max_length=30)),
                ('canal', models.CharField(choices=[('email', 'Correo electrónico')], default='email', max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('programada_para', models.DateTimeField(db_index=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('enviada', models.BooleanField(default=False)),
                ('leida', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='inicio.contrato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='inicio.pago')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['estado'], name='inicio_cont_estado_d0765a_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['numero_departamento', 'estado'], name='inicio_cont_numero__6cf5e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='contrato_fecha_fin_gt_inicio'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('tarifa_mensual__gt', 0)), name='contrato_tarifa_mensual_positive'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('numero_departamento',), name='unique_departamento_contrato_activo'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['contrato', 'estado'], name='inicio_pago_contrat_e5b08d_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['periodo'], name='inicio_pago_periodo_e88a8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pago_monto_positive'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(fields=('contrato', 'periodo'), name='unique_pago_contrato_periodo'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'enviada', 'leida'], name='inicio_noti_usuario_eae382_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo', 'programada_para'], name='inicio_noti_tipo_425c26_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.UniqueConstraint(condition=models.Q(('pago__isnull', False)), fields=('pago', 'tipo'), name='unique_notif_por_pago_tipo'),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.UniqueConstraint(condition=models.Q(('contrato__isnull', False), ('tipo', 'fin_contrato')), fields=('contrato', 'tipo'), name='unique_notif_fin_contrato'),
        ),
    ]
