# Generated by Django 5.1.4 on 2025-08-10 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_contrato_pago_notificacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
        migrations.AlterField(
            model_name='contrato',
            name='arrendatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_departamento',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tarifa_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='periodo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
