# Generated by Django 5.1.4 on 2025-09-07 20:50

import django.db.models.deletion
import inicio.validacion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_contrato_options_alter_notificacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceCrearAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Crear Administrador',
                'verbose_name_plural': 'Crear Administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('reglamento', 'Reglamento'), ('anexo', 'Anexo'), ('otro', 'Otro')], db_index=True, max_length=20)),
                ('archivo', models.FileField(upload_to='documentos/', validators=[inicio.validacion.validar_extension, inicio.validacion.validar_tamano])),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('mensaje', models.TextField(blank=True, max_length=2000)),
                ('atendido', models.BooleanField(db_index=True, default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observaciones', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', validators=[inicio.validacion.validar_extension, inicio.validacion.validar_tamano]),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_vencimiento'], name='inicio_pago_fecha_v_9dc391_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['validado'], name='inicio_pago_validad_7db973_idx'),
        ),
        migrations.AddField(
            model_name='documento',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inicio.contrato'),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='atendido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos_atendidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tipo'], name='inicio_docu_tipo_43a6e8_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['subido_en'], name='inicio_docu_subido__40a313_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['usuario'], name='inicio_docu_usuario_57cdcf_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['atendido'], name='inicio_pros_atendid_bcc3af_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['fecha'], name='inicio_pros_fecha_19b240_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['email'], name='inicio_pros_email_e991a0_idx'),
        ),
    ]
